main: com.sekwah.advancedportals.legacyspigot.AdvancedPortalsPlugin
name: AdvancedPortals
version: ${pluginVersion}
author: sekwah41
description: An advanced portals plugin for bukkit.
api-version: 1.8.8
softdepend: [PlaceholderAPI]
commands:
  portal:
    description: The main command for the advanced portals
    aliases: [portals, aportals, advancedportals]
    usage: /<command>
  destination:
    description: Can be used to access portal destinations.
    aliases: [desti]
    usage: /<command>
permissions: ${permissions}
