main: com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin
name: AdvancedPortals
version: 0.9.2
author: sekwah
description: An advanced portals plugin for bukkit.
api-version: 1.13

softdepend:
  - WorldEdit

commands:
  advancedportals:
    description: The main command for the advanced portals
    aliases: [portals, aportals, portal, ap]
    usage: /<command>
    permission: advancedportals.portalcommand
  destination:
    description: Can be used to access portal destinations.
    aliases: [desti]
    usage: /<command>
    permission: advancedportals.desti
permissions:
  advancedportals.*:
    description: Gives access to all commands
    default: op
    children:
      advancedportals.createportal: true
      advancedportals.portal: true
      advancedportals.build: true
      advancedportals.desti: true
  advancedportals.createportal:
    description: Allows you to create portals
    default: op
  advancedportals.createportal.commandlevel.*:
    description: Gives access to all level raisers
    default: false
    children:
      advancedportals.createportal.commandlevel.op: true
      advancedportals.createportal.commandlevel.bungee: true
      advancedportals.createportal.commandlevel.perms: true
      advancedportals.createportal.commandlevel.console: true
  advancedportals.createportal.commandlevel.op:
    description: Allows you to run portal commands as op
    default: false
  advancedportals.createportal.commandlevel.perms:
    description: Allows you to run portal commands with * permission
    default: false
  advancedportals.createportal.commandlevel.bungee:
    description: Allows you to run portal commands through bungee
    default: false
  advancedportals.createportal.commandlevel.console:
    description: Executes command in the console
    default: false
  advancedportals.portal:
    description: Allows use of portal commands
    default: op
  advancedportals.portalcommand:
    description: Access to the portal command. This is seperate to allow access to portal warps without the rest.
    default: true
  advancedportals.build:
    description: Allows you to build in the portal regions
    default: op
  advancedportals.desti:
    description: Gives access to all desti commands
    default: op
  advancedportals.warp:
    description: Access to the warp command
    default: op
  advancedportals.warp.*:
    description: Access to all warps
    default: op
