main: com.sekwah.advancedportals.spigot.AdvancedPortalsPlugin
name: AdvancedPortals
version: ${pluginVersion}
author: sekwah41
description: An advanced portals plugin for bukkit.
api-version: 1.13
commands:
  portal:
    description: The main command for the advanced portals
    aliases: [portals, aportals, advancedportals]
    usage: /<command>
  destination:
    description: Can be used to access portal destinations.
    aliases: [desti]
    usage: /<command>
permissions:
${permissions}
