when:
  - event: [push, manual]

matrix:
  include:
    - project: "spigot"
    - project: "legacyspigot"
    - project: "folia"

steps:
  - name: snapshot-${project}
    image: codeberg.org/sekwah/advanced-portals/advanced-portals-ci:dev
    environment:
      DISCORD_WEBHOOK:
        from_secret: DISCORD_WEBHOOK
    commands:
      - gradle ${project}:discordupload --no-watch-fs --no-daemon