when:
  - event: push

matrix:
  platform: ["codeberg-tiny"]
  include:
    - project: "spigot"
    - project: "legacyspigot"
    - project: "folia"

steps:
  - name: snapshot-${project}
    image: codeberg.org/sekwah/advanced-portals/advanced-portals-ci:dev
    commands:
      - free -m
      - gradle ${project}:build --no-watch-fs --no-daemon